/**
 * CodeBuddy model catalog — generated by scripts/generate-model-catalog.mjs
 * from https://models.dev/api.json + live /v3/config availability probes.
 * Loaded once per process; regenerate the JSON when catalogs change.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export interface ModelCost {
  input: number | null;
  output: number | null;
  cache_read?: number | null;
  cache_write?: number | null;
}

export interface ModelSpec {
  modelsDevRef: string | null;
  name: string | null;
  reasoning: boolean;
  toolCall: boolean;
  structuredOutput: boolean;
  temperature: boolean;
  knowledge: string | null;
  releaseDate: string | null;
  modalities: { input: string[]; output: string[] } | null;
  limit: { context: number | null; output: number | null } | null;
  cost: ModelCost | null;
}

export interface CatalogModel {
  id: string;
  sites: Array<"cn" | "intl">;
  status: "spec-ok" | "no-external-spec";
  spec: ModelSpec | null;
}

export type Site = "cn" | "intl";

let cached: Array<CatalogModel> | null = null;

/** Resolve which site an upstream credential talks to. */
export function siteForBase(apiBase: string | undefined | null): Site {
  return typeof apiBase === "string" && apiBase.includes("codebuddy.ai") ? "intl" : "cn";
}

export function loadCatalog(): Array<CatalogModel> {
  if (cached) return cached;
  const here = dirname(fileURLToPath(import.meta.url));
  const raw = JSON.parse(readFileSync(join(here, "catalog.generated.json"), "utf8")) as {
    models: Array<CatalogModel>;
  };
  cached = raw.models;
  return cached;
}

export function catalogForSite(site: Site): Array<CatalogModel> {
  return loadCatalog().filter((m) => m.sites.includes(site));
}

export function specForId(id: string): ModelSpec | null {
  return loadCatalog().find((m) => m.id === id)?.spec ?? null;
}
